config/routes.rb
GenRap::Application.routes.draw do

  root :to => 'exams#pending'

  resources :users, :groups, :master_questions, :exam_definitions, :exams
  
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "def", to: "exam_definition#new"
  match "results/exam/:id", to: "exams#results", as: "exam_results"
  match "create/exam/:id", to: "exams#create", as: "create_exam"
  match "pending", to: "exams#pending"
  match "edit/:id", to: "exam_definition#edit"
  match "mystats", to: "stats#mystats"
  match "profstats", to: "stats#profstats"

  match "master_question/concepts_for_question" => "master_questions#concepts_for_question"
  match "master_question/subconcepts_for_question" => "master_questions#subconcepts_for_question"
  match "master_question/filtered_master_questions" => "master_questions#filtered_master_questions"
  match "master_question/transmiting_JSON" => "master_questions#transmiting_JSON"
  match "master_question/get_languages" => "master_questions#get_languages"

  match "exam/get_exams" => "exams#get_exams"

  match "exam_definition/exam_def" => "exam_definition#exam_def"

  match "group/get_groups" => "groups#get_groups"

  match "user/get_users" => "users#get_users"
  match "user/get_current_user" => "users#get_current_user"
  match "user/set_users_cantake" => "users#set_users_cantake"
  match "user/set_user_cantake_own" => "users#set_user_cantake_own"
  match "user/change_admin/:id" => "users#change_admin"
  match "user/change_professor/:id" => "users#change_professor"
  match "user/change_student/:id" => "users#change_student"

end

app/models/exam_definition.rb
#encoding: utf-8
class ExamDefinition < ActiveRecord::Base
  belongs_to :master_exam
  belongs_to :master_question

  validates :master_exam,		:presence => true
  validates :master_question,	:presence => true
  validates :questionNum,	:presence => true,
  							:numericality => { :only_integer => true,
  										:greater_than_or_equal_to => 0 }
  validates :weight,		:presence => true,
  							:numericality => {  :greater_than_or_equal_to => 0.0,
  												:less_than_or_equal_to => 1.0 }

  attr_accessible :questionNum, :weight, :master_exam, :master_question
end

app/controllers/exam_definition_controller.rb
#encoding: utf-8
class ExamDefinitionController < ApplicationController

  before_filter :authenticate_user

	def new
		@examDefinition = ExamDefinition.new
		@master_questions = MasterQuestion.all_languages
		@examUsers = nil

    if check_prof
      render "new"
    else
      render "new_student"
    end
	end

	def create
    if check_prof
  		@examDefinition = ExamDefinition.new(params[:examID])
  		@examDefinition.utype = 0
  		
  		if @examDefinition.save
  			flash[:notice] = "Definición de examen creada de manera exitosa."
  		else
  			flash[:error] = "Los datos no son válidos."
  		end

  		redirect_to root_path
    else
        flash[:error] = "Acceso restringido."
        redirect_to root_path
    end
	end

	# def edit
	# end

	# def update
	# end

	# def destroy
	# end

	# def index
	# end

	def exam_def
    #este no debería de ir aquí pero marca error al intentarlo hacer en otro controlador
    #parece que una vez que hago un get en este controlador, ya no puedo cambiarlo.
    #por lo tanto los queries los voy a hacer aquí
    hash = params[:hash]
    exam_name = params[:exam_name]
    number_of_attempts = params[:number_of_attempts]
    creationYear = params[:creationYear].to_i
    creationMonth = params[:creationMonth].to_i
    creationDay = params[:creationDay].to_i
    creationHour = params[:creationHour].to_i
    creationMinute = params[:creationMinute].to_i
    startYear = params[:startYear].to_i
    startMonth = params[:startMonth].to_i
    startDay = params[:startDay].to_i
    startHour = params[:startHour].to_i
    startMinute = params[:startMinute].to_i
    endYear = params[:endYear].to_i
    endMonth = params[:endMonth].to_i
    endDay = params[:endDay].to_i
    endHour = params[:endHour].to_i
    endMinute = params[:endMinute].to_i

    timeZone = "Monterrey"

    user = User.find_by_id session[:user_id]
    master_exam = MasterExam.create(
      attempts: number_of_attempts,
      name: exam_name,
      dateCreation: Time.strptime("#{creationYear}-#{creationMonth}-#{creationDay} #{creationHour}:#{creationMinute}", '%Y-%m-%d %H:%M').in_time_zone(timeZone),
      startDate: Time.strptime("#{startYear}-#{startMonth}-#{startDay} #{startHour}:#{startMinute}", '%Y-%m-%d %H:%M').in_time_zone(timeZone),
      finishDate: Time.strptime("#{endYear}-#{endMonth}-#{endDay} #{endHour}:#{endMinute}", '%Y-%m-%d %H:%M').in_time_zone(timeZone),
      user: user
    )
        
    hash.each_with_index do |(key, value), index|
      ExamDefinition.create( 
        master_question: MasterQuestion.find_by_id( hash[key]['master_question_id'].to_i ),
        master_exam: MasterExam.find_by_id(master_exam.id),
        questionNum: index+1, 
        weight: hash[key]['value'].to_f
      )
    end

    if check_prof
      flash[:notice] = "Examen agregado exitosamente"
    else
      flash[:notice] = "Ejercicio creado exitosamente"
    end

    respond_to do |format|
      format.json { render json: hash.to_json }
    end

	end
end

app/controllers/exam_definitions_controller.rb
#encoding: utf-8
class ExamDefinitionsController < ApplicationController

	# before_filter :authenticate_user, :only => [:index, :new, :create]

	def index
		if check_admin or check_prof
			@eds = ExamDefinition.all
		else
			flash[:error] = "Usted necesita ser un administrador o profesor para ver todos los exámenes definidos."
			redirect_to(root_path)
		end
	end



	def new
		@ed = ExamDefinition.new
	end



	def create
		@ed = ExamDefinition.new(params[:exam_definition])
		
		if @ed.save
			flash[:notice] = "Pregunta agregada a definición de manera exitosa."
			redirect_to(exam_definitions_path)
		else
			flash[:error] = "Datos de la pregunta o examen maestro no válidos."
			redirect_to(new_exam_definition_path)
		end
	end


	def show
		@ed = ExamDefinition.find(params[:id])
	end


	def edit
		@ed = ExamDefinition.find(params[:id])
	end


	def update
		@ed = ExamDefinition.find(params[:id])
	 
		if @ed.update_attributes!(params[:exam_definition])
			flash[:notice] = 'La pregunta del examen maestro fue actualizada de manera correcta.'
	    else
	    	flash[:error] = "No se pudieron actualizar los datos de la pregunta."
	    end

	    redirect_to(@ed)
	end


	def destroy
		@ed = ExamDefinition.find(params[:id])
		@ed.destroy

		redirect_to :action => 'index'
	end

end

app/helpers/exam_definition_helper.rb
module ExamDefinitionHelper
end

app/helpers/exam_definitions_helper.rb
module ExamDefinitionsHelper
end

app/views/exam_definitions/_form.html.erb
<%= simple_form_for(@ed) do |f| %>
	<fieldset>
		<!-- <legend>Registro de nueva pregunta maestra en examen maestro</legend> -->

		<%= f.input :master_exam_id, :label => 'ID Examen Maestro' %>
		<%= f.input :master_question_id, :label => 'ID Pregunta Maestra' %>
		<%= f.input :questionNum, :label => 'Número pregunta' %>
		<%= f.input :weight, :label => 'Peso' %>

		<div class="control-group">
			<div class="controls">
				<%= f.button :submit %>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/exam_definitions/edit.html.erb
<h1>Editar pregunta de exámen maestro</h1>
 
<%= render 'form' %>
 
<%= link_to 'Mostrar', @ed %> |
<%= link_to 'Atrás', exam_definitions_path %>

app/views/exam_definitions/index.html.erb
<h1>Exámenes Definidos</h1>
 
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Exámen Maestro</th>
      <th>Pregunta</th>
      <th>No. Pregunta</th>
      <th>Peso</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
  <% @eds.each do |ed| %>
    <tr>
      <td><%= ed.master_exam_id %></td>
      <td><%= ed.master_question_id %></td>
      <td><%= ed.questionNum %></td>
      <td><%= ed.weight %></td>
      <td><%= link_to 'Mostrar', ed %></td>
      <td><%= link_to 'Editar', edit_exam_definition_path(ed) %></td>
      <td><%= link_to 'Borrar', ed, :confirm => '¿Está seguro que quiere borrar esta pregunta de la definición del exámen?', :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>
 
<br />
 
<%= link_to 'Nueva Pregunta en Exámen Maestro', new_exam_definition_path %>

app/views/exam_definitions/new.html.erb
<% content_for = "Creación de pregunta de éxamen maestro" %>

<div class="hero-unit">
	<h1>Registro de nueva pregunta para exámen maestro</h1>

	<%= render 'form' %>

	<% if @ed.errors.any? %>
		<ul>
			<% for message_error in @ed.errors.full_messages %>
			<li>- <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/exam_definitions/show.html.erb
<p>
  <b>Exámen Maestro:</b>
  <%= @ed.master_exam.name %>
</p>

<p>
  <b>Pregunta Maestra:</b>
  <%= @ed.master_question_id %>
</p>

<p>
  <b>Número de pregunta:</b>
  <%= @ed.questionNum %>
</p>

<p>
  <b>Peso:</b>
  <%= @ed.weight %>
</p>
 
 
<%= link_to 'Editar', edit_exam_definition_path(@ed) %>

<% if check_admin %>
	| <%= link_to 'Definición de Exámenes', exam_definitions_path %>
<% end %>