config/routes.rb
GenRap::Application.routes.draw do

  root :to => 'exams#pending'

  resources :users, :groups, :master_questions, :exam_definitions, :exams
  
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "def", to: "exam_definition#new"
  match "results/exam/:id", to: "exams#results", as: "exam_results"
  match "create/exam/:id", to: "exams#create", as: "create_exam"
  match "pending", to: "exams#pending"
  match "edit/:id", to: "exam_definition#edit"
  match "mystats", to: "stats#mystats"
  match "profstats", to: "stats#profstats"

  match "master_question/concepts_for_question" => "master_questions#concepts_for_question"
  match "master_question/subconcepts_for_question" => "master_questions#subconcepts_for_question"
  match "master_question/filtered_master_questions" => "master_questions#filtered_master_questions"
  match "master_question/transmiting_JSON" => "master_questions#transmiting_JSON"
  match "master_question/get_languages" => "master_questions#get_languages"

  match "exam/get_exams" => "exams#get_exams"

  match "exam_definition/exam_def" => "exam_definition#exam_def"

  match "group/get_groups" => "groups#get_groups"

  match "user/get_users" => "users#get_users"
  match "user/get_current_user" => "users#get_current_user"
  match "user/set_users_cantake" => "users#set_users_cantake"
  match "user/set_user_cantake_own" => "users#set_user_cantake_own"
  match "user/change_admin/:id" => "users#change_admin"
  match "user/change_professor/:id" => "users#change_professor"
  match "user/change_student/:id" => "users#change_student"

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user#, :inverse_of => :group
  has_and_belongs_to_many :users#, :inverse_of => :groups

  attr_accessible :name, :user, :user_ids, :id

  validates :name,	:presence => true
  validates :user,	:presence => true
end

app/controllers/groups_controller.rb
#encoding: utf-8
class GroupsController < ApplicationController

	before_filter :authenticate_user, :only => [:index, :new, :create]

	def index
		if check_admin
			@groups = Group.all
		elsif check_prof
			@groups = @current_user.groups
		else
			flash[:error] = "Usted necesita ser un administrador para accesar esta página."
			redirect_to(root_path)
		end
	end

	def new
		@group = Group.new
	end

	def create
		if check_prof
			@group = Group.new(params[:group])
			@group.user = @current_user
			if !@group.users.include? @current_user
				@group.users << @current_user
			end
			
			if @group.save
				flash[:notice] = "Grupo creado de manera exitosa."
				redirect_to(groups_path)
			else
				flash[:error] = "Datos del grupo no válidos."
				redirect_to(new_group_path)
			end
		else
			flash[:error] = "Acceso restringido."
			redirect_to root_path
		end
	end

	def show
		if check_prof
			@group = Group.find(params[:id])
		else
			flash[:error] = "Acceso restringido."
			redirect_to root_path
		end
	end

	def edit
		if check_prof
			@group = Group.find(params[:id])
		else
			flash[:error] = "Acceso restringido."
			redirect_to root_path
		end
	end

	def update
		if check_prof
			@group = Group.find(params[:id])
		 
			if @group.update_attributes(params[:group])
				flash[:notice] = 'El grupo fue actualizado de manera correcta.'
		    else
		    	flash[:error] = "No se pudieron actualizar los datos del grupo."
		    end

		    redirect_to(@group)
		else
			flash[:error] = "Acceso restringido."
			redirect_to root_path
		end
	end

	def destroy
		if check_prof
			@group = Group.find(params[:id])
			@group.destroy

			redirect_to :action => 'index'
		else
			flash[:error] = "Acceso restringido."
			redirect_to root_path
		end
	end

	def get_groups
		if check_prof
			@groups = Group.where(user_id: session[:user_id]).select("name, id")
		    respond_to do |format|
		      format.json { render json: @groups.to_json }
		    end
		end
  	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
	<fieldset>
		<!-- <legend>Registro de usuario</legend> -->

		<%= f.input :name, :label => 'Nombre del grupo' %>
		<%= f.association :users, as: :check_boxes, :label => 'Integrantes', label_method: :username %>

		<div class="control-group">
			<div class="controls">
				<%= f.button :submit %>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/groups/edit.html.erb
<h1>Editar grupo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Mostrar', @group %> |
<%= link_to 'Atrás', groups_path %>

app/views/groups/index.html.erb
<h1>Grupos</h1>
 
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Dueño</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
  <% @groups.each do |group| %>
    <tr>
      <td><%= group.name %></td>
      <td><%= group.user.username %></td>
      <td><%= link_to 'Mostrar', group %></td>
      <td><%= link_to 'Editar', edit_group_path(group) %></td>
      <td><%= link_to 'Borrar', group, :confirm => '¿Está seguro que quiere borrar este grupo?', :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>
 
<br />
 
<%= link_to 'Nuevo Grupo', new_group_path %>

app/views/groups/new.html.erb
<% content_for = "Creación de grupo" %>

<div class="hero-unit">
	<h1>Registro de nuevo grupo</h1>

	<%= render 'form' %>

	<% if @group.errors.any? %>
		<ul>
			<% for message_error in @group.errors.full_messages %>
			<li>- <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/groups/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @group.name %>
</p>

<p>
  <b>Dueño:</b>
  <%= @group.user.username %>
</p>

<p>
	<b>Miembros:</b>
	<% for user in @group.users %>
		<%= user.username %>
	<% end %>
</p>
 
 
<%= link_to 'Editar', edit_group_path(@group) %>

<% if check_admin %>
	| <%= link_to 'Grupos', groups_path %>
<% end %>

app/views/groups/signup.html.erb
<% content_for = "Sign Up" %>

<div class="hero-unit">
	<h1>Registro de nuevo usuario</h1>

	<%= render 'form' %>

	<% if @user.errors.any? %>
		<ul>
			<% for message_error in @user.errors.full_messages %>
			<li>- <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>