config/routes.rb
GenRap::Application.routes.draw do

  root :to => 'exams#pending'

  resources :users, :groups, :master_questions, :exam_definitions, :exams
  
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "def", to: "exam_definition#new"
  match "results/exam/:id", to: "exams#results", as: "exam_results"
  match "create/exam/:id", to: "exams#create", as: "create_exam"
  match "pending", to: "exams#pending"
  match "edit/:id", to: "exam_definition#edit"
  match "mystats", to: "stats#mystats"
  match "profstats", to: "stats#profstats"

  match "master_question/concepts_for_question" => "master_questions#concepts_for_question"
  match "master_question/subconcepts_for_question" => "master_questions#subconcepts_for_question"
  match "master_question/filtered_master_questions" => "master_questions#filtered_master_questions"
  match "master_question/transmiting_JSON" => "master_questions#transmiting_JSON"
  match "master_question/get_languages" => "master_questions#get_languages"

  match "exam/get_exams" => "exams#get_exams"

  match "exam_definition/exam_def" => "exam_definition#exam_def"

  match "group/get_groups" => "groups#get_groups"

  match "user/get_users" => "users#get_users"
  match "user/get_current_user" => "users#get_current_user"
  match "user/set_users_cantake" => "users#set_users_cantake"
  match "user/set_user_cantake_own" => "users#set_user_cantake_own"
  match "user/change_admin/:id" => "users#change_admin"
  match "user/change_professor/:id" => "users#change_professor"
  match "user/change_student/:id" => "users#change_student"

end

app/models/exam.rb
#encoding: utf-8
class Exam < ActiveRecord::Base
  belongs_to :master_exam
  belongs_to :user
  has_many :questions

  validates :state,	:presence => true
  validates :score,	:presence => true,
  					:numericality => { :greater_than_or_equal_to => 0.0,
  										:less_than_or_equal_to => 100.0 }

  attr_accessible :date, :questions_attributes, :score
  accepts_nested_attributes_for :questions

  before_save :check_attempts

  # private
	  def check_attempts
	  	state = self.state.to_i
		attempts = Exam.where("master_exam_id = ? and user_id = ?", self.master_exam_id, self.user_id).size
		allowedAttempts = MasterExam.find(self.master_exam_id).attempts
		if attempts > allowedAttempts || state >= 2
			false
		elsif state >= -1
		  	state = state + 1
		  	self.state = state.to_s
	  	else
	  		false
	  	end
	  end


  def self.createInstance(master_exam_id, user_id)
  		# session = Hash.new
  		# session[:user_id] = 9

  		ActiveRecord::Base.transaction do
			exam = Exam.new

			# Create exam
			exam.master_exam = MasterExam.find(master_exam_id)
			exam.user = User.find user_id
			exam.state = "-1"
			exam.date = Time.now
			exam.score = 0
			
			user = User.find(user_id)
			
			if exam.master_exam.users.include? user
				attemptN = Exam.where("master_exam_id = ? and user_id = ?", master_exam_id, user_id).size

				if attemptN < exam.master_exam.attempts
					exam.attemptnumber = attemptN + 1

					if exam.save
						# flash[:notice] = "Examen creado de manera exitosa."
						puts "Examen creado de manera exitosa."
					else
						# flash[:error] = "No se pudo crear el examen."
						puts "No se pudo crear el examen."
						raise ActiveRecord::Rollback
					end
				else
					# flash[:error] = "Se han agotado los attempts."
					puts "Se han agotado los attempts."
					raise ActiveRecord::Rollback
				end
			else
				# flash[:error] = "Usuario no puede tomar este examen."
				puts "Usuario no puede tomar este examen."
				raise ActiveRecord::Rollback
			end

			# Create questions
			e_definition = ExamDefinition.where("master_exam_id = ?", master_exam_id)
			for mQuestion in e_definition
				master_question = MasterQuestion.find(mQuestion.master_question_id)
				inquiry = master_question.inquiry

				# We generate random question
				randomizer = master_question.randomizer
				full_randomizer_path = File.dirname(__FILE__) + "/../helpers/r/" + randomizer + '.rb'
				load full_randomizer_path
				puts "loaded " + full_randomizer_path
				values = randomize(inquiry)
				# puts "values " + values.to_s

				# We generate values, correctAns
				solver = master_question.solver
				full_solver_path = File.dirname(__FILE__) + "/../helpers/s/" + solver + '.rb'
				load full_solver_path
				puts "loaded " + full_solver_path
				answers, correctAns = solve(inquiry, values)
				# puts "answers " + answers.to_s
				# puts "correctAns " + correctAns.to_s

				# We finally create the question
				question = Question.new
				# puts "exam " + exam.to_s
				question.exam = exam
				question.master_question = master_question
				question.questionNum = mQuestion.questionNum
				question.values = values
				question.answers = answers
				question.correctAns = correctAns
				question.givenAns = ""

				if question.save
					# flash[:notice] = "Pregunta creada de manera exitosa."
					puts "Pregunta creada de manera exitosa."
				else
					# flash[:error] = "No se pudo crear la pregunta."
					puts "No se pudo crear la pregunta."
					raise ActiveRecord::Rollback
				end
			end #end for

			#Return exam
			exam

		end  #end transaction
	end #end method

end

app/controllers/exams_controller.rb
#encoding: utf-8
class ExamsController < ApplicationController

	helper_method :who_cantake_masterExam

	before_filter :authenticate_user, :except => [:who_cantake_masterExam]

	def new
		@exam = Exam.new
	end

	def index
		if check_admin
			@masterExams = MasterExam.all
		elsif check_prof
			@masterExams = MasterExam.where("user_id = ?", @current_user.id)
		else
			flash[:error] = "Acceso restringido."
			redirect_to(root_path)
		 end
	end

	def pending
		@masterExams = Array.new
		@attempts_exams = Array.new

		@masterExercises = Array.new
		@exer_info = Array.new

		# Se obtienen los examenes cuya fecha de inicio sea menor a la actual y fecha de termino sea mayor a la actual
		# Además, estos deben ser creados por personas diferentes al usuario actual
		availableExams = MasterExam.where("startDate <= ? AND finishDate >= ? AND user_id <> ?", Time.now, Time.now, @current_user.id)
		
		# Para cada uno de estos examenes, se agrega el master exam y los intentos actuales a los arreglos correspondientes
		availableExams.each do |masterExam|
			# Se obtienen los usuarios relacionados con este examen
			validUsers = who_cantake_masterExam(masterExam.id)
			# Se valida que el usuario actual sea un usuario valido y que haya intentos restantes
			if validUsers.include?(@current_user.id) and Exam.where("master_exam_id = ? and user_id = ?", masterExam.id, @current_user.id).size < masterExam.attempts
				@masterExams.push(masterExam)
				# Se agrega a la lista de intentos, la cantidad de intentos del examen encontrado
				@attempts_exams.push(Exam.where("master_exam_id = ? and user_id = ?", masterExam.id, @current_user.id).size)
			end
		end

		# Se obtienen los examenes (ejercicios) creados por uno mismo, como ejercicios
		availableExercices = MasterExam.where("user_id = ?", @current_user.id)
		
		# Para cada uno de estos examenes, se agrega el master exam y el promedio de los intentos actuales a los arreglos correspondientes
		availableExercices.each do |masterExam|
			# Se obtienen los usuarios relacionados con este examen
			validUsers = who_cantake_masterExam(masterExam.id)
			# Se valida que el usuario actual sea un usuario valido
			if validUsers.include?(@current_user.id)
				actual_exams = Exam.where("master_exam_id = ? and user_id = ?", masterExam.id, @current_user.id)
				@masterExercises.push(masterExam)
				if actual_exams.length > 0
					grade = actual_exams.map { |e| e.score }.inject{|sum,x| sum + x }
					grade = grade / actual_exams.length.to_f
				else
					grade = "-"
				end
				@exer_info.push([grade, actual_exams.length])
			end
		end
	end

	def create
		masterExam = MasterExam.find(params[:id])
		creatorId = masterExam.user_id
		available = false
		if creatorId == @current_user.id
			# La fecha de creación no importa, es un ejercicio
			available = true
		else
			#La fecha de creación si importa, es un examen de alguien más
			if masterExam.startDate <= Time.now && masterExam.finishDate >= Time.now
				available = true
			end
		end
		@attempts = Exam.where("master_exam_id = ? and user_id = ?", params[:id], @current_user.id).size
		validUsers = who_cantake_masterExam(masterExam.id)

		if available && (check_prof || validUsers.include?(@current_user.id))

			# Se crea una instancia del examen para el usuario actual
			exam = Exam.createInstance(params[:id],@current_user.id)
			if exam != nil
				# Redirigir a editar el examen para contestarlo
				redirect_to :action => "edit", :id => exam.id
			elsif @attempts >= masterExam.attempts
				flash[:notice] = "Numero de intentos excedido."
				redirect_to(pending_path)
			else
				flash[:error] = "Error al crear el exámen. Intentos actuales: "+@attempts.to_s+"."
				redirect_to(pending_path)
			end
			#Modificar el estado del master exam de dicho usuario
			# @masterExam = MasterExam.find(params[:id])
			#Disminuir un intento cuando se entra al examen
			# @masterExam.attempts = @masterExam.attempts - 1;
		else
			flash[:error] = "Exámen no disponible."
			redirect_to(pending_path)
		end
	end


	def edit
		# Se verifica que el administrador sea el que está editando o que el examen sea del usuario actual y que el estado del examen sea 0 (creado)
		if check_prof || (@current_user.id.to_i == Exam.find(params[:id]).user_id.to_i && Exam.find(params[:id]).state.to_i == 0)
			# Declarar el examen como comenzado
			@exam = Exam.find(params[:id])
			# Se guarda el examen para cambiarse a comenzado
			if !@exam.save
				flash[:error] = "Error al obtener el examen."
				redirect_to(pending_path)
			end
		else
			flash[:error] = "Acceso restringido."
			redirect_to(pending_path)
		end
	end


	def show
		if check_prof || @current_user.id == Exam.find(params[:id]).user_id
			@exam = Exam.find(params[:id])
		else
			flash[:error] = "Acceso restringido."
			redirect_to(pending_path)
		end
	end

	def update
		if check_prof || @current_user.id == Exam.find(params[:id]).user_id
			@exam = Exam.find(params[:id])
			
			masterExam = @exam.master_exam

			# Checar que la fecha del examen sea valida
			if masterExam.startDate <= Time.now && masterExam.finishDate >= Time.now
				score = 0
				masterExamId = masterExam.id

				# Para cada pregunta, se verifica la respuesta
				@exam.questions.each do |question|

					masterQuestionId = question.master_question_id
					questionId = params[":questions"][question.id.to_s]
					givenAns = questionId["givenAns"]
					question.update_attributes(givenAns: givenAns)

					# Si la respuesta dada es correcta, se agrega la cantidad al score
					if givenAns == question.correctAns
						questionNum = question.questionNum
						examDef = ExamDefinition.where("master_exam_id = ? and master_question_id = ? and questionNum = ?", masterExamId, masterQuestionId, questionNum).first
						weight = examDef.weight
						score = score + weight*100
					end
				end

				# Se actualiza el score del examen
			    if @exam.update_attributes(score: score)
					flash[:notice] = 'El exámen fue registrado de manera correcta.'
			    else
			    	flash[:error] = "Error al guardar el exámen."
			    	redirect_to(root_path)
			    end
		    	redirect_to :action => "results", :id => @exam.id
		    else
		    	flash[:error] = "Examen no disponible."
		    	redirect_to(root_path)
		    end
		else
			flash[:error] = "Acceso restringido."
			redirect_to(root_path)
		end
	end

	def results
		exam = Exam.find(params[:id])
		validUsers = Array.new
		validUsers.push(exam.user_id)

		masterExam = MasterExam.find(exam.master_exam_id)
		examCreator = masterExam.user_id

		validUsers.push(examCreator)


		if check_prof || validUsers.include?(@current_user.id)
			@exam = exam
		else
			flash[:error] = "Acceso restringido."
			redirect_to(root_path)
		end
	end

	#gets a list of users that can take the masterExam
	# private
		def who_cantake_masterExam(masterExamId)
			validUsers = Array.new

			masterExam = MasterExam.find(masterExamId)
			masterExam.cantakes.each do |cantake|
				validUsers.push(cantake.user_id) 
			end
			validUsers
		end
 	
end

app/helpers/exams_helper.rb
module ExamsHelper

	def format_values(values)
		JSON.parse("{" << values.gsub("-","").gsub(/(\^\d+)/,'"\\1"').gsub("\n",",").sub(",","").gsub(/(.*),(.*)/,'\\1\\2') << "}")
	end

	def format_answers(answers)
		answers.gsub("-","").gsub("\n",",").sub(",","").gsub(/(.*),(.*)/,'\\1\\2').split(/,/)
	end

end

app/views/exams/_form.html.erb
<%= simple_form_for @exam do |exam_field| %>
	<fieldset>
		<% answers = Array.new %>
		<% @exam.questions.each do |question| %>
			<% inquiry = question.master_question.inquiry %>
			<!-- gsub 1 no se debe de necesitar, hay algo mal en question.values -> randomizer -->
			<% parsed = format_values(question.values) %>
			<% parsed = parsed.stringify_keys() %>
			<% parsed.each do |key, value| %>
				<p><% inquiry = inquiry.gsub(key,value.to_s) %></p>
			<% end %>
			<p><%= question.questionNum.to_s+".  "+inquiry %></p>

			<%= simple_fields_for ":questions[]", question do |question_field| %>
				<% answers = format_answers(question.answers) %>
				<%= question_field.select :givenAns, answers.map{ |ansNum| [ansNum.split(": ").second, ansNum.split(": ").first] } %>
			<% end %>
		<% end %>

		<div class="control-group">
			<div class="controls">
				<%= exam_field.button :submit, "Enviar" %>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/exams/_form_show.html.erb
<%= simple_form_for @exam do |exam_field| %>
	<fieldset>
		<% answers = Array.new %>
		<% @exam.questions.each do |question| %>
			<% inquiry = question.master_question.inquiry %>
			<!-- gsub 1 no se debe de necesitar, hay algo mal en question.values -> randomizer -->
			<% parsed = format_values(question.values) %>
			<% parsed = parsed.stringify_keys() %>
			<% parsed.each do |key, value| %>
				<p><% inquiry = inquiry.gsub(key,value.to_s) %></p>
			<% end %>
			<p><%= question.questionNum.to_s+".  "+inquiry %></p>

			<%= simple_fields_for ":questions[]", question do |question_field| %>
				<% answers = format_answers(question.answers) %>
				<%= question_field.select :givenAns, answers.map{ |ansNum| [ansNum.split(": ").second, ansNum.split(": ").first] } %>
			<% end %>
		<% end %>
	</fieldset>
<% end %>

app/views/exams/edit.html.erb
<div class="hero-unit">
	<h3 style="text-align: center;">Exámen</h3>

	<%= render 'form' %>

	<% if @exam.errors.any? %>
		<ul>
			<% for message_error in @exam.errors.full_messages %>
			<li>- <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/exams/index.html.erb
<div class="table">
  <% if @masterExams != nil %>
    
    <%= table_for @masterExams, html: {id: 'exams', class: 'summary table table-striped table-bordered table-condensed'} do -%>
      <% column title: 'Nombre' do |masterExam| %>
        <% link_to(masterExam.name, create_exam_path(masterExam.id), confirm: "Are you sure?") %>
      <% end %>
      <% column :attempts, title: 'Intentos máximos' %>
      <% column :startDate, title: 'Inicio' %>
      <% column :finishDate, title: 'Fin' %>
    <% end %>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>No hay exámenes disponibles</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>
</div>

app/views/exams/pending.html.erb
<div class="table">

  <h3>Exámenes Disponibles</h3>
  <% if @masterExams.length > 0 && @attempts_exams.length > 0 %>
    <% count = 0 %>

    <table class="summary table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <th>Nombre</th><th>Intentos actuales</th><th>Intentos máximos</th><th>Inicio</th><th>Fin</th>
        </tr>
        <% @masterExams.each do |masterExam| %>
          <tr>
            <td><%= link_to(masterExam.name, create_exam_path(masterExam.id), confirm: "¿Seguro que deseas tomar este exámen?") %></td>
            <td><%= @attempts_exams[count] %><% count = count + 1 %></td>
            <td><%= masterExam.attempts %></td>
            <td><%= masterExam.startDate %></td>
            <td><%= masterExam.finishDate %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>No hay exámenes disponibles</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>


  <h3>Ejercicios Disponibles</h3>
  <% if @masterExercises.length > 0 %>
    <% count = 0 %>

    <table class="summary table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <th>Nombre</th>
          <th>Calificación Promedio</th>
          <th>Veces Tomado</th>
        </tr>
        <% @masterExercises.each do |masterExam| %>
          <tr>
            <td><%= link_to(masterExam.name, create_exam_path(masterExam.id)) %></td>
            <td><%= @exer_info[count][0] %></td>
            <td><%= @exer_info[count][1] %><% count = count + 1 %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>No hay ejercicios disponibles</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>
</div>

app/views/exams/results.html.erb
<div class="table">
  <% if @exam != nil %>
    
    <table id="results" class="summary table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <th>Intento</th>
          <th>Calificación</th>
          <th>Fecha</th>
        </tr>
        <tr>
          <td><%= @exam.attemptnumber %></td>
          <td><%= @exam.score %></td>
          <td><%= @exam.updated_at %></td>
        </tr>
      </tbody>
    </table>

    <% if check_admin %>
      <%= link_to "Continuar", exams_path, class: "btn" %>
    <% else %>
      <%= link_to "Continuar", pending_path, class: "btn" %>
    <% end %>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>Hubo un error al extraer los resultados de su examen.</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>
</div>

app/views/exams/show.html.erb
<div class="hero-unit">
	<h3 style="text-align: center;">Exámen</h3>

	<%= render 'form_show' %>

	<% if check_admin %>
		<%= link_to "Regresar", request.referer, {class: "btn"} %>
	<% else %>
		<%= link_to "Regresar", request.referer, {class: "btn"} %>
	<% end %>

	<% if @exam.errors.any? %>
		<ul>
			<% for message_error in @exam.errors.full_messages %>
			<li>- <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>